source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'bootstrap-sass'
gem 'coffee-rails', '~> 4.1.0'
gem 'dotenv-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'mysql2', '>= 0.3.13', '< 0.4'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
# gem 'slim-rails'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'react-rails', '~> 1.0'
gem 'marked-rails'

group :development, :test do
  gem 'byebug'
  gem 'capistrano', '~> 3.2.1'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-sidekiq', github: 'seuros/capistrano-sidekiq'
  gem 'capistrano3-unicorn'
  gem 'database_rewinder'
  gem 'factory_girl_rails'
  gem 'ffaker'
  gem 'hirb'
  gem 'hirb-unicode'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'rspec_junit_formatter'
  gem 'rspec-rails', '~> 3.0'
  gem 'rubocop'
  gem 'seed-fu', '~> 2.3'
  gem 'spring'
  gem 'web-console', '~> 2.0'
  gem 'yard'
end
